# CICD Pipeline for running Microsoft Fabric specific python scripts

# specific branch build with batching: https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  batch: true
  branches:
    include:
    - '*'
    # could be something like this to trigger only on shortcut branches
    # - '*-shortcut'

pool: 'jugis_laptop'  # windows OS asumed, for Linux the scripts below need to be slightly modified

parameters:
- name: python.version # Required as first property.
  displayName: python.version # Human-readable name for the parameter.
  type: string
  default: '3.10'
- name: FABRIC_USERNAME
  displayName: FABRIC_USERNAME
  type: string
  default: tech_user@MngEnvMCAP312279.onmicrosoft.com
- name: FABRIC_PASSWORD
  displayName: FABRIC_PASSWORD
  type: string
  default: $(FABRIC_PASSWORD)


steps:


- script: |
    call python -m venv .venv
    call .venv\Scripts\activate.bat
    call pip install -r requirements.txt
  displayName: 'Install dependencies'


- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'deploy.py'
    pythonInterpreter: '.venv\Scripts\python.exe'